kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-secure-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
