apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: px-alpha-sc
    name: px-alpha-pvc
    namespace: alpha
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
