apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationClone
metadata:
  name: <name of the object>
  namespace: <admin namspace>
spec:
  sourceNamespace: <source namespace>
  destinationNamespace: <destination namespace>
