apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-secure-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  openstorage.io/auth-secret-name: px-k8s-user
  openstorage.io/auth-secret-namespace: portworx
