kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: finance-pvc
   namespace: finance
   annotations:
     volume.beta.kubernetes.io/storage-class: px-secure-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
