apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackup
metadata:
  name: backup
  namespace: <source_namespace>
spec:
  backupLocation: <backuplocation_object>
  namespaces:
  - <namespace_to_backup>
  reclaimPolicy: Delete
  selectors:
  preExecRule:
  postExecRule:
