kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-proxy-volume-volume
provisioner: kubernetes.io/portworx-volume
parameters:
  proxy_endpoint: "nfs://<NODE01_IP>"
  proxy_nfs_exportpath: "/mnt/nfs_share"
allowVolumeExpansion: true