apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: mongodb-presnap-rule
rules:
  - podSelector:      
      role: mongo
    actions:
    - type: command      
      value: mongo --eval "printjson(db.fsyncLock())"
