kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: <name>
   namespace: <namespace>
   annotations:
     volume.beta.kubernetes.io/storage-class: <storage class>
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
